//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SmartClockSrlLector.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class checkin
    {
        public int id { get; set; }
        public Nullable<int> employeeID { get; set; }
        public Nullable<System.DateTime> checkDate { get; set; }
        public string checkHour { get; set; }
        public string observations { get; set; }
    
        public virtual employees employees { get; set; }
    }
}
